name: Predicción meteorológica semanal

on:
  schedule:
    - cron: "0 * * * 0"   # Cada domingo, cada hora (UTC)
  workflow_dispatch:

jobs:
  generar_y_enviar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Comprobar hora Madrid
        id: hora
        run: |
          python - <<EOF
          from datetime import datetime
          import pytz
      
          now = datetime.now(pytz.timezone("Europe/Madrid"))
          #ejecutar = now.hour == 23 # Cambiar a ejecutar = True para ejecución ya, sino a la hora determinada ejecutar = now.hour == 23
          es_hora = now.hour == 23
          es_manual = "${{ github.event_name }}" == "workflow_dispatch"
          ejecutar = es_hora or es_manual
          
          with open("${GITHUB_OUTPUT}", "a") as f:
              f.write(f"ejecutar={str(ejecutar).lower()}\n")
      
          print(f"Hora Madrid: {now.strftime('%H:%M')}, ejecutar={ejecutar}")
          EOF



      - name: Generar PDF
        if: steps.hora.outputs.ejecutar == 'true'
        run: python scripts/generar_prediccion_meteo_pdf.py

      - name: Enviar email
        if: steps.hora.outputs.ejecutar == 'true'
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_DESTINO: ${{ secrets.EMAIL_DESTINO }}
        run: python scripts/enviar_email.py
